DROP TABLE TESTGEOM CASCADE CONSTRAINTS;

DROP TABLE LINESTRINGTEST CASCADE CONSTRAINTS;

DROP TABLE MULTILINESTRINGTEST CASCADE CONSTRAINTS;

DROP TABLE POLYGONTEST CASCADE CONSTRAINTS;

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='LINESTRINGTEST';

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='MULTILINESTRINGTEST';

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='POLYGONTEST';