-- DROP ENTRIES IN META-DATA TABLE
DELETE FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME IN ('LRS_2D','LRS_2D_M','LRS_3D','LRS_3D_M');

-- DROP INDEXES
DROP INDEX IDX_LRS_2D_GEOM;
DROP INDEX IDX_LRS_2D_M_GEOM;
DROP INDEX IDX_LRS_3D_GEOM;
DROP INDEX IDX_LRS_3D_M_GEOM;

-- MAKE ENTRIES INTO USER_SDO_GEOM_METADATA SO TABLES CAN BE INDEXED
INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
  VALUES (
  'LRS_2D',
  'GEOMETRY',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('X', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Y', 0, 100000, 0.001)
     ),
  null
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
  VALUES (
  'LRS_2D_M',
  'GEOMETRY',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('X', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Y', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('M', 0, 500, 0.005)
     ),
  null
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
  VALUES (
  'LRS_3D',
  'GEOMETRY',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('X', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Y', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Z', 0, 100000, 0.001)
     ),
  null
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
  VALUES (
  'LRS_3D_M',
  'GEOMETRY',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('X', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Y', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('Z', 0, 100000, 0.001),
    SDO_DIM_ELEMENT('M', 0, 500, 0.005)
     ),
  null
);

--CREATE SPATIAL INDEXES
CREATE INDEX IDX_LRS_2D_GEOM ON LRS_2D(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2');

CREATE INDEX IDX_LRS_2D_M_GEOM ON LRS_2D_M(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2');

CREATE INDEX IDX_LRS_3D_GEOM ON LRS_3D(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2');

CREATE INDEX IDX_LRS_3D_M_GEOM ON LRS_3D_M(GEOMETRY)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2');